router:
    routes:
        home:
            type: Zend\Mvc\Router\Http\Literal
            options:
                route: /
                defaults:
                    controller: Application\Controller\Index
                    action: index
        application:
            type: Literal
            options:
                route: /application
                defaults:
                    __NAMESPACE__: Application\Controller
                    controller: Index
                    action: index
            may_terminate: true
            child_routes:
                default:
                    type: Segment
                    options:
                        route: /[:controller[/:action]]
                        constraints:
                            controller: '[a-zA-Z][a-zA-Z0-9_-]*'
                            action: '[a-zA-Z][a-zA-Z0-9_-]*'
service_manager:
    abstract_factories:
    - Zend\Cache\Service\StorageCacheAbstractServiceFactory
    - Zend\Log\LoggerAbstractServiceFactory
    aliases:
        translator: MvcTranslator
translator:
    locale: en_US
    translation_file_patterns:
    -   type: gettext
        base_dir: /home/edcosta/projects/skeleton-application/module/Application/config/../language
        pattern: '%s.mo'
controllers:
    invokables:
        Application\Controller\Index: Application\Controller\IndexController
view_manager:
    display_not_found_reason: true
    display_exceptions: true
    doctype: HTML5
    not_found_template: error/404
    exception_template: error/index
    template_map:
        layout/layout: /home/edcosta/projects/skeleton-application/module/Application/config/../view/layout/layout.phtml
        application/index/index: /home/edcosta/projects/skeleton-application/module/Application/config/../view/application/index/index.phtml
        error/404: /home/edcosta/projects/skeleton-application/module/Application/config/../view/error/404.phtml
        error/index: /home/edcosta/projects/skeleton-application/module/Application/config/../view/error/index.phtml
    template_path_stack:
    - /home/edcosta/projects/skeleton-application/module/Application/config/../view
console:
    router:
        routes: [
            ]